import type { Permission } from "./rbac";

export type Plan = "FREE" | "BASIC" | "PRO" | "ENTERPRISE";
export type Addon = "HRMS" | "PAYROLL" | "SERVICES" | "ADVANCED_ANALYTICS" | "WHITE_LABEL";

export const PLAN_PERMISSIONS: Record<Plan, Permission[]> = {
  FREE: [
    "DASHBOARD_OVERVIEW_VIEW",
    "SETTINGS_PROFILE_VIEW",
    "SETTINGS_PROFILE_EDIT",
  ],
  BASIC: [
    "DASHBOARD_OVERVIEW_VIEW",
    "SETTINGS_PROFILE_VIEW",
    "SETTINGS_PROFILE_EDIT",
    "CLIENTS_VIEW",
    "APPOINTMENTS_VIEW",
  ],
  PRO: [
    "DASHBOARD_OVERVIEW_VIEW",
    "DASHBOARD_OPERATIONS_VIEW",
    "SETTINGS_PROFILE_VIEW",
    "SETTINGS_PROFILE_EDIT",
    "CLIENTS_VIEW",
    "CLIENTS_EDIT",
    "SERVICES_VIEW",
    "SERVICES_EDIT",
    "APPOINTMENTS_VIEW",
    "APPOINTMENTS_EDIT",
    "INVOICES_VIEW",
  ],
  ENTERPRISE: [
    "DASHBOARD_OVERVIEW_VIEW",
    "DASHBOARD_OPERATIONS_VIEW",
    "DASHBOARD_MYWORK_VIEW",
    "SETTINGS_PROFILE_VIEW",
    "SETTINGS_PROFILE_EDIT",
    "SETTINGS_ORG_VIEW",
    "SETTINGS_ORG_EDIT",
    "SETTINGS_TEAM_VIEW",
    "SETTINGS_TEAM_INVITE",
    "SETTINGS_TEAM_EDIT_ROLES",
    "SETTINGS_SECURITY_VIEW",
    "SETTINGS_SECURITY_EDIT",
    "SETTINGS_BILLING_VIEW",
    "SETTINGS_BILLING_EDIT",
    "CLIENTS_VIEW",
    "CLIENTS_EDIT",
    "SERVICES_VIEW",
    "SERVICES_EDIT",
    "APPOINTMENTS_VIEW",
    "APPOINTMENTS_EDIT",
    "INVOICES_VIEW",
    "INVOICES_EDIT",
    "REPORTS_VIEW",
  ],
};

export const ADDON_PERMISSIONS: Record<Addon, Permission[]> = {
  HRMS: [
    "SETTINGS_TEAM_VIEW",
    "SETTINGS_TEAM_INVITE",
    "SETTINGS_TEAM_EDIT_ROLES",
  ],
  PAYROLL: [
    "SETTINGS_BILLING_VIEW",
    "INVOICES_VIEW",
    "INVOICES_EDIT",
  ],
  SERVICES: [
    "SERVICES_VIEW",
    "SERVICES_EDIT",
  ],
  ADVANCED_ANALYTICS: [
    "REPORTS_VIEW",
  ],
  WHITE_LABEL: [
    "SETTINGS_BRANDING_VIEW",
    "SETTINGS_BRANDING_EDIT",
  ],
};
