export const ROLES = ["OWNER", "ADMIN", "MANAGER", "STAFF", "ACCOUNTANT"] as const;
export type Role = (typeof ROLES)[number];

export const PERMISSIONS = [
  "SETTINGS_PROFILE_VIEW",
  "SETTINGS_PROFILE_EDIT",

  "SETTINGS_ORG_VIEW",
  "SETTINGS_ORG_EDIT",

  "SETTINGS_TEAM_VIEW",
  "SETTINGS_TEAM_INVITE",
  "SETTINGS_TEAM_EDIT_ROLES",

  "SETTINGS_SECURITY_VIEW",
  "SETTINGS_SECURITY_EDIT",

  "SETTINGS_SECURITY_LOGIN_HISTORY_VIEW",
  "SETTINGS_SECURITY_FORCE_LOGOUT",
  "SETTINGS_SECURITY_IP_RULES_VIEW",
  "SETTINGS_SECURITY_IP_RULES_EDIT",

  "SETTINGS_BILLING_VIEW",
  "SETTINGS_BILLING_EDIT",

  "SETTINGS_CLIENT_PORTAL_VIEW",
  "SETTINGS_CLIENT_PORTAL_EDIT",

  "SETTINGS_BRANDING_VIEW",
  "SETTINGS_BRANDING_EDIT",

  "SETTINGS_THEME_VIEW",
  "SETTINGS_THEME_EDIT",

  "SETTINGS_NOTIFICATIONS_VIEW",
  "SETTINGS_NOTIFICATIONS_EDIT",

  "DASHBOARD_OVERVIEW_VIEW",
  "DASHBOARD_OPERATIONS_VIEW",
  "DASHBOARD_MYWORK_VIEW",

  "CLIENTS_VIEW",
  "CLIENTS_EDIT",
  "SERVICES_VIEW",
  "SERVICES_EDIT",
  "APPOINTMENTS_VIEW",
  "APPOINTMENTS_EDIT",
  "INVOICES_VIEW",
  "INVOICES_EDIT",
  "REPORTS_VIEW",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export type RolePermissions = Record<Role, readonly Permission[]>;

export const ROLE_PERMISSIONS: RolePermissions = {
  OWNER: [
    "SETTINGS_PROFILE_VIEW", "SETTINGS_PROFILE_EDIT",
    "SETTINGS_ORG_VIEW", "SETTINGS_ORG_EDIT",
    "SETTINGS_TEAM_VIEW", "SETTINGS_TEAM_INVITE", "SETTINGS_TEAM_EDIT_ROLES",
    "SETTINGS_SECURITY_VIEW", "SETTINGS_SECURITY_EDIT",
    "SETTINGS_SECURITY_LOGIN_HISTORY_VIEW", "SETTINGS_SECURITY_FORCE_LOGOUT",
    "SETTINGS_SECURITY_IP_RULES_VIEW", "SETTINGS_SECURITY_IP_RULES_EDIT",
    "SETTINGS_BILLING_VIEW", "SETTINGS_BILLING_EDIT",
    "SETTINGS_CLIENT_PORTAL_VIEW", "SETTINGS_CLIENT_PORTAL_EDIT",
    "SETTINGS_BRANDING_VIEW", "SETTINGS_BRANDING_EDIT",
    "SETTINGS_THEME_VIEW", "SETTINGS_THEME_EDIT",
    "SETTINGS_NOTIFICATIONS_VIEW", "SETTINGS_NOTIFICATIONS_EDIT",

    "DASHBOARD_OVERVIEW_VIEW", "DASHBOARD_OPERATIONS_VIEW",
    "CLIENTS_VIEW", "CLIENTS_EDIT",
    "SERVICES_VIEW", "SERVICES_EDIT",
    "APPOINTMENTS_VIEW", "APPOINTMENTS_EDIT",
    "INVOICES_VIEW", "INVOICES_EDIT",
    "REPORTS_VIEW",
  ],
  ADMIN: [
    "SETTINGS_PROFILE_VIEW", "SETTINGS_PROFILE_EDIT",
    "SETTINGS_ORG_VIEW", "SETTINGS_ORG_EDIT",
    "SETTINGS_TEAM_VIEW", "SETTINGS_TEAM_INVITE", "SETTINGS_TEAM_EDIT_ROLES",
    "SETTINGS_SECURITY_VIEW",
    "SETTINGS_SECURITY_LOGIN_HISTORY_VIEW",
    "SETTINGS_BILLING_VIEW",
    "SETTINGS_CLIENT_PORTAL_VIEW", "SETTINGS_CLIENT_PORTAL_EDIT",
    "SETTINGS_BRANDING_VIEW", "SETTINGS_BRANDING_EDIT",
    "SETTINGS_THEME_VIEW", "SETTINGS_THEME_EDIT",
    "SETTINGS_NOTIFICATIONS_VIEW", "SETTINGS_NOTIFICATIONS_EDIT",

    "DASHBOARD_OVERVIEW_VIEW", "DASHBOARD_OPERATIONS_VIEW",
    "CLIENTS_VIEW", "CLIENTS_EDIT",
    "SERVICES_VIEW", "SERVICES_EDIT",
    "APPOINTMENTS_VIEW", "APPOINTMENTS_EDIT",
    "INVOICES_VIEW",
    "REPORTS_VIEW",
  ],
  MANAGER: [
    "SETTINGS_PROFILE_VIEW", "SETTINGS_PROFILE_EDIT",
    "SETTINGS_THEME_VIEW", "SETTINGS_THEME_EDIT",
    "SETTINGS_NOTIFICATIONS_VIEW", "SETTINGS_NOTIFICATIONS_EDIT",
    "SETTINGS_CLIENT_PORTAL_VIEW",

    "DASHBOARD_OPERATIONS_VIEW",
    "CLIENTS_VIEW",
    "SERVICES_VIEW",
    "APPOINTMENTS_VIEW",
  ],
  STAFF: [
    "SETTINGS_PROFILE_VIEW", "SETTINGS_PROFILE_EDIT",
    "SETTINGS_NOTIFICATIONS_VIEW", "SETTINGS_NOTIFICATIONS_EDIT",

    "DASHBOARD_MYWORK_VIEW",
    "APPOINTMENTS_VIEW",
  ],
  ACCOUNTANT: [
    "SETTINGS_PROFILE_VIEW", "SETTINGS_PROFILE_EDIT",
    "SETTINGS_BILLING_VIEW", "SETTINGS_BILLING_EDIT",
    "SETTINGS_NOTIFICATIONS_VIEW",

    "DASHBOARD_OVERVIEW_VIEW",
  ],
};

export function hasPermission(
  userPerms: readonly Permission[] | undefined,
  perm: Permission
): boolean {
  return !!userPerms?.includes(perm);
}

export function buildPermissionsFromRole(role: Role): Permission[] {
  return [...ROLE_PERMISSIONS[role]];
}

export function isValidRole(role: string | undefined | null): role is Role {
  return !!role && ROLES.includes(role.toUpperCase() as Role);
}

export function normalizeRole(role: string | undefined | null): Role | null {
  if (!role) return null;
  const upper = role.toUpperCase() as Role;
  return ROLES.includes(upper) ? upper : null;
}
